export const assets = {
  home: {
    hero: {
      avatarSmile: require("@images/home/hero/avatar-smile.webp"),
      av1: require("@images/home/hero/av1.png"),
      av2: require("@images/home/hero/av2.png"),
      dribble: require("@images/home/hero/dribble.webp"),
      github: require("@images/home/hero/github.webp"),
      instagram: require("@images/home/hero/instagram.webp"),
      linkedin: require("@images/home/hero/linkedin.webp"),
      quadrilateral: require("@images/home/hero/quadrilateral.webp"),
      triangle: require("@images/home/hero/triangle.webp"),
      twistedTorus: require("@images/home/hero/twisted-torus.webp"),
      zigZag: require("@images/home/hero/zig-zag.webp"),
      logo: require("@images/home/hero/14.png"),
    },
    letsConnect: {
      avatarBigSmile: require("@images/home/letsConnect/avatar-big-smile.webp"),
      x: require("@images/home/letsConnect/x.jpg"),
      github: require("@images/home/letsConnect/github.webp"),
      gmail: require("@images/home/letsConnect/gmail.webp"),
      instagram: require("@images/home/letsConnect/instagram.webp"),
      linkedin: require("@images/home/letsConnect/linkedin.webp"),
    },
    myLatestProject: {
      figma: require("@images/home/myLatestProject/figma.webp"),
      pp: require("@images/home/myLatestProject/pp.png"),
      vs: require("@images/home/myLatestProject/vs.jpg"),
      rocket: require("@images/home/myLatestProject/rocket.webp"),
      suitcase: require("@images/home/myLatestProject/suitcase.webp"),
      projects: {
        portfolioWebsite: require("@images/home/myLatestProject/projects/portfolio-website.webp"),
        grabn: require("@images/home/myLatestProject/projects/1.png"),
        ham: require("@images/home/myLatestProject/projects/4.png"),
        sel: require("@images/home/myLatestProject/projects/3.png"),
        ecell: require("@images/home/myLatestProject/projects/6.png"),
        oldP: require("@images/home/myLatestProject/projects/3.png"),
        culfest: require("@images/home/myLatestProject/projects/2.png"),
        gdsc: require("@images/home/myLatestProject/projects/gdsc.png"),
        culfestcount: require("@images/home/myLatestProject/projects/culfestcount.png"),
        culfestaf: require("@images/home/myLatestProject/af.png"),
      },
    },
    quote: {
      bulb: require("@images/home/quote/bulb.webp"),
      heart: require("@images/home/quote/heart.webp"),
      paintKit: require("@images/home/quote/paint-kit.webp"),
      teaCup: require("@images/home/quote/tea-cup.webp"),
    },
    technologyStack: {
      // expo: require("@images/home/technologyStack/expo.webp"),
      // expressJs: require("@images/home/technologyStack/express-js.webp"),
      javascript: require("@images/home/technologyStack/javascript.webp"),
      // laravel: require("@images/home/technologyStack/laravel.webp"),
      nextJs: require("@images/home/technologyStack/nextjs.png"),
      // planetScale: require("@images/home/technologyStack/planet-scale.webp"),
      // prisma: require("@images/home/technologyStack/prisma.webp"),
      reactJs: require("@images/home/technologyStack/react-js.webp"),
      // reactNative: require("@images/home/technologyStack/react-native.webp"),
      tailwindCss: require("@images/home/technologyStack/tailwindcss.webp"),
      typescript: require("@images/home/technologyStack/Ts.png"),
      python: require("@images/home/technologyStack/py.png"),
      electron: require("@images/home/technologyStack/electronjs.png"),
      flask: require("@images/home/technologyStack/flask.png"),
      node: require("@images/home/technologyStack/nodejs.svg"),
      selenium: require("@images/home/technologyStack/Selenium.png"),
      gsap: require("@images/home/technologyStack/gsap.svg"),
      threejs: require("@images/home/technologyStack/3js.png"),
      docker: require("@images/home/technologyStack/Docker.jpg"),
      aws: require("@images/home/technologyStack/aws.jpg"),
      gcp: require("@images/home/technologyStack/gcp.png"),
    },
  },
};
